### ISSUE TITLE
Possible bad interaction when cy.get() -> alias returns an array

### ISSUE THREAD

**Issue by samelawrence** [bahmutov/cypress-command-chain#3]
I'm not sure what's going on here, but I have a bad interaction with `map` from the plugin.

![Screen Shot 2022-02-27 at 1 33 49 AM](https://user-images.githubusercontent.com/170246/155871334-4ab16c0f-a37e-40a1-8f1f-c2ed6ca89c78.png)

**Comment by bahmutov** [comment]
@samelawrence I have added a guard to the function, if you have the test sample showing the crash, let me know so I can ensure it runs without a problem

**Comment by samelawrence** [comment]
@bahmutov I'm still seeing the issue in `1.1.2` with this piece of code:

```typescript
//List of Items in catalog element selector
cy.get("div[class*= 'ptv-information-main-id'] span").as("itemListElement");

//Getting the text of the first element from the list
cy.get("@itemListElement")
  .first()
  .invoke("text")
  .then((x) => (initialValue = x));
```

The error throws when the second block is reached: `Cannot read properties of undefined (reading 'map')`

```typescript
  4 | const stringify = (args) => {
  5 |   return args
> 6 |     .map((x) => {
    | ^
  7 |       if (typeof x === 'function') {
  8 |         return (x.name ? x.name : 'cb') + '()'
  9 |       }
```

**Comment by bahmutov** [comment]
@samelawrence I do not think you are using the latest version, that function should have
```js
// TODO: handle functions etc
const stringify = (args) => {
  if (!Array.isArray(args)) {
    return ''
  }

  return args
    .map((x) => {
```

**Comment by samelawrence** [comment]
@bahmutov I force re-installed `1.1.2` into my package dependencies and things seem to be working ok now. Not sure what I did wrong previously, but thanks for the prompt to try again. 👍
